# Generated by Django 3.0.8 on 2020-08-14 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnDown',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('ideal', models.IntegerField()),
                ('actual', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dods',
            fields=[
                ('filename', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('filename', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('filename', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Throughput',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('requirements', models.IntegerField()),
                ('features', models.IntegerField()),
                ('opportunities', models.IntegerField()),
                ('enhancements', models.IntegerField()),
                ('bugs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=20, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=200, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('filename', 'owner')},
            },
        ),
    ]
