# Generated by Django 3.0.8 on 2020-08-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='throughput',
            old_name='enchancements',
            new_name='enhancements',
        ),
    ]
