# Generated by Django 3.0.8 on 2020-08-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tastic', '0003_dods_features_stories'),
    ]

    operations = [
        migrations.AddField(
            model_name='dods',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='features',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stories',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
