# Generated by Django 3.0.8 on 2020-08-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tastic', '0004_auto_20200812_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dods',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='dods',
            name='view_url',
        ),
        migrations.RemoveField(
            model_name='features',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='features',
            name='view_url',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='download_url',
        ),
        migrations.RemoveField(
            model_name='stories',
            name='view_url',
        ),
    ]
